#version: "3.9"

services:

  web:
    # build: .
    command: poetry run gunicorn -c gunicorn.conf.py config.wsgi:application
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SETTINGS_MODULE=config.settings
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    image: username/habit-tracker:${IMAGE_TAG:-latest}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      # - .:/app       # <-- точка — это корень проекта, где лежит manage.py
    working_dir: /app   # <-- важно: чтобы manage.py был в текущей директории
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-net

  celery:
    build: .
    # Для воркера Celery
    command: poetry run celery -A config worker -l INFO --pool=solo
    volumes:
      - .:/app       # <-- точка — это корень проекта, где лежит manage.py
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - app-net

  beat:
    build: .
    # Планировщик периодических задач
    command: poetry run celery -A config beat -l INFO
    volumes:
      - .:/app        # <-- точка — это корень проекта, где лежит manage.py
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
    networks:
      - app-net

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # можно убрать, если доступ только из контейнеров
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net
    ports:
      - "6379:6379"

  migrate:
    build: .
    command: poetry run python manage.py migrate
    volumes:
      - .:/app        # <-- точка — это корень проекта, где лежит manage.py
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"  # раскомментируй, когда будет SSL
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./static:/var/www/static:ro  # если собираешь static отдельно
    depends_on:
      web:
        condition: service_healthy
    networks:
      - app-net

volumes:
  postgres_data:
  redisdata:

networks:
  app-net:
    driver: bridge
