# Generated by Django 5.0.4 on 2026-06-04 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения",
                        max_length=128,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time_action",
                    models.DateTimeField(
                        help_text="Укажите время выполнения",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие",
                        max_length=256,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, если привычка приятная",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения в днях",
                        verbose_name="Периодичность выполнения в днях",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=256,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "durations",
                    models.IntegerField(
                        default=120,
                        help_text="Укажите продолжительность выполнения привычки в секундах",
                        verbose_name="Продолжительность выполнения привычки в секундах",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите публичность",
                        verbose_name="Публичность",
                    ),
                ),
                (
                    "habit_pleasant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
